# Generated by Django 4.2 on 2024-04-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_grade_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='status',
            field=models.CharField(blank=True, choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], max_length=10, null=True),
        ),
    ]
