# Generated by Django 4.2 on 2024-04-15 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_subject_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
        migrations.AddField(
            model_name='subject',
            name='register',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.register'),
        ),
    ]
