# Generated by Django 4.2 on 2024-04-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_subject_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='course',
        ),
    ]
