# Generated by Django 4.2 on 2024-04-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_grade_grade_alter_grade_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Repproved', 'Repproved'), ('No grade', 'No grade')], max_length=10, null=True),
        ),
    ]
