# Generated by Django 4.2 on 2024-04-15 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_student_course_register_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='done',
        ),
        migrations.AddField(
            model_name='subject',
            name='register',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='app.register'),
            preserve_default=False,
        ),
    ]
